name: YouTube Radio Live

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Télécharger les musiques
        run: |
          mkdir -p Musiques
          wget -i <(grep -E '^https?://' playlist.txt) -P Musiques

      - name: Vérifier les fichiers dans le dossier Musiques
        run: ls -l Musiques

      - name: Corriger les chemins dans playlist.txt
        run: sed -i 's|https://.*/|file ./Musiques/|g' playlist.txt

      - name: Afficher le contenu de playlist.txt
        run: cat playlist.txt

      - name: Installer FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Diffuser la radio sur YouTube
        run: |
          ffmpeg -re -stream_loop -1 -f concat -safe 0 -i playlist.txt -ignore_loop 0 -i background.gif \
          -filter_complex "[1:v]scale=1280:720:flags=lanczos,format=yuva420p[v];[v]loop=-1:1:0[vout]" \
          -map "[vout]" -map 0:a -c:v libx264 -crf 23 -preset veryfast -c:a aac -b:a 128k \
          -f flv "rtmp://a.rtmp.youtube.com/live2/q0m7-ev92-uh81-juw8-ctb8"
          
